.PHONY: clean All

All:
	@echo "----------Building project:[ nisy - Debug ]----------"
	@cd "nisy" && "$(MAKE)" -f  "nisy.mk"
clean:
	@echo "----------Cleaning project:[ nisy - Debug ]----------"
	@cd "nisy" && "$(MAKE)" -f  "nisy.mk" clean
